appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: CKbAbVWYfNVD/AhuwAHmVf8YUnmwJvSgGKaKyfua1FW1IgYt9Mf3203F4VfaHQMRN9yhkEazTXFHbFCtLk+hTN0rSuE3exBjU/jzP2vSrQthgpAQsysUTjBBcUHaT0SkS1tmAdQMicQBdBk3F16xynqEs4ZHSo608CqLE1TxQBSD0w1AZkanjPCC6C2XNUWLCKubv348XSe3rL5OiqetDTur5ogE4N/pCR3NbRsbGWcHzZkRtJXl628VZcs8qPHq6u2bpeYVF4hjV0rXpLfrvZLihGDF/vk2mG0f+OACtoKhTJfaey8iirE5K+s+k9bo50CMrqJVNt2wlxLFWMVLvTTH8Yl9VEuprwmEpEe0updS1oVqHQqChn0Hrq5UIB4sqdyIXr+2njBqStgR2NXWk6HF3VzQ/NndNnIAKT+fMTOKLsaJWwnTDzVKIUAHdfnTMgzyxoerSfHTSFWrOheXmi/Z+MygW9y1Z8LQdS/8TDGifInOW6H/qpw+QxeBJhnYVYGLpS7O/ljpmwB/uruFhvmbI/MmgSNtWBiu5RL6WWaLSGsFLuor2dIUhvmpqv/rKM+RgxAthvjbOuXT2zeS8u9iBMekgfwD6WJ3c07ic1px3kzailxdvDw7+4r5mj3mm/aQzaIzE5LFE0BxFuT+HpAvN5tcMuJJozjsF4n/1G0=}
conda_forge_output_validation: true
